
LMP_ERR_SUCCESS = 0
LMP_ERR_NOT_SUPPORTED = 1
LMP_ERR_INVALID_COMMAND = 2
LMP_ERR_INVALID_PARAMETER = 3
LMP_ERR_INVALID_DEVICE = 4
LMP_ERR_UNREGISTERED = 5
LMP_ERR_CLEAR_MSG_UNAUTHORIZED = 6
LMP_ERR_CRYPT_MSG = 7
LMP_ERR_TIMEOUT = 8
LMP_ERR_CONNECT_ERROR = 9
LMP_ERR_MEMORY_FAIL = 10
LMP_ERR_MEMORY_FULL = 11
LMP_ERR_INVALID_SIZE = 12
LMP_ERR_SERVICE_NOT_READY = 19
LMP_ERR_ITEM_NOT_FOUND = 20

serial_errors_str_dict = {
LMP_ERR_SUCCESS:'SUCCESS',
LMP_ERR_NOT_SUPPORTED:'ERR_NOT_SUPPORTED',
LMP_ERR_INVALID_COMMAND:'ERR_INVALID_COMMAND',
LMP_ERR_INVALID_PARAMETER:'ERR_INVALID_PARAMETER',
LMP_ERR_INVALID_DEVICE:'ERR_INVALID_DEVICE',
LMP_ERR_UNREGISTERED:'ERR_UNREGISTERED',
LMP_ERR_CLEAR_MSG_UNAUTHORIZED:'ERR_CLEAR_MSG_UNAUTHORIZED',
LMP_ERR_CRYPT_MSG:'ERR_CRYPT_MSG',
LMP_ERR_TIMEOUT:'ERR_TIMEOUT',
LMP_ERR_CONNECT_ERROR:'ERR_CONNECT_ERROR',
LMP_ERR_MEMORY_FAIL:'ERR_MEMORY_FAIL',
LMP_ERR_MEMORY_FULL:'ERR_MEMORY_FULL',
LMP_ERR_INVALID_SIZE:'ERR_INVALID_SIZE',
LMP_ERR_SERVICE_NOT_READY:'ERR_SERVICE_NOT_READY',
LMP_ERR_ITEM_NOT_FOUND:'ERR_ITEM_NOT_FOUND'
}
